# Generated by Django 5.1.7 on 2025-04-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chatbot",
            "0004_rename_user_chatroom_created_by_chatroom_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_bot",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("question", "User Question"),
                    ("response", "Chatbot Response"),
                    ("system", "System Message"),
                ],
                default="question",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="chatbot.chatmessage",
            ),
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
