# Generated by Django 5.1.7 on 2025-03-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livechat", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatparticipant",
            name="room",
        ),
        migrations.RemoveField(
            model_name="chatparticipant",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="chatroom",
            options={},
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="description",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="hashtags",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatParticipant",
        ),
    ]
