# Generated by Django 5.1.7 on 2025-03-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_alter_comment_author_alter_comment_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="thumbnail/%Y/%m/%d"),
        ),
    ]
