# Generated by Django 5.1.7 on 2025-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_alter_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.URLField(max_length=255),
        ),
    ]
