# Generated by Django 5.1.7 on 2025-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_alter_uploadedimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
