# Generated by Django 5.1.6 on 2025-03-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivate_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
