# Generated by Django 5.1.7 on 2025-03-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_allerge_userallerge_user_allergies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Allerge",
            new_name="Allergy",
        ),
        migrations.RemoveField(
            model_name="user",
            name="allergies",
        ),
        migrations.DeleteModel(
            name="UserAllerge",
        ),
    ]
