# Generated by Django 5.1.7 on 2025-03-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_allerge_allergy_remove_user_allergies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allergies",
            field=models.ManyToManyField(blank=True, to="accounts.allergy"),
        ),
    ]
