# Generated by Django 5.1.7 on 2025-03-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_allergies"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferredCuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuisine", models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name="allergy",
            old_name="Ingredient",
            new_name="ingredient",
        ),
        migrations.AddField(
            model_name="user",
            name="diet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_picture/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_cuisine",
            field=models.ManyToManyField(blank=True, to="accounts.preferredcuisine"),
        ),
    ]
