# Generated by Django 5.1.7 on 2025-03-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_preferredcuisine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NicknamePrefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="NicknameSuffix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
