# Generated by Django 5.1.7 on 2025-03-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_nicknameprefix_nicknamesuffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
