# Generated by Django 5.1.7 on 2025-03-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
